package com.persistentes;
// Generated 23/07/2015 03:35:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Casaplaya generated by hbm2java
 */
public class Casaplaya  implements java.io.Serializable {


     private String codigo;
     private Propietario propietario;
     private String poblacion;
     private Integer nhabitaciones;
     private Integer nbanos;
     private Integer ncocinas;
     private Integer ncomedores;
     private Integer nestacionamientos;
     private Boolean estadoactual;
     private Set paquetes = new HashSet(0);

    public Casaplaya() {
    }

	
    public Casaplaya(String codigo) {
        this.codigo = codigo;
    }
    public Casaplaya(String codigo, Propietario propietario, String poblacion, Integer nhabitaciones, Integer nbanos, Integer ncocinas, Integer ncomedores, Integer nestacionamientos, Boolean estadoactual, Set paquetes) {
       this.codigo = codigo;
       this.propietario = propietario;
       this.poblacion = poblacion;
       this.nhabitaciones = nhabitaciones;
       this.nbanos = nbanos;
       this.ncocinas = ncocinas;
       this.ncomedores = ncomedores;
       this.nestacionamientos = nestacionamientos;
       this.estadoactual = estadoactual;
       this.paquetes = paquetes;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Propietario getPropietario() {
        return this.propietario;
    }
    
    public void setPropietario(Propietario propietario) {
        this.propietario = propietario;
    }
    public String getPoblacion() {
        return this.poblacion;
    }
    
    public void setPoblacion(String poblacion) {
        this.poblacion = poblacion;
    }
    public Integer getNhabitaciones() {
        return this.nhabitaciones;
    }
    
    public void setNhabitaciones(Integer nhabitaciones) {
        this.nhabitaciones = nhabitaciones;
    }
    public Integer getNbanos() {
        return this.nbanos;
    }
    
    public void setNbanos(Integer nbanos) {
        this.nbanos = nbanos;
    }
    public Integer getNcocinas() {
        return this.ncocinas;
    }
    
    public void setNcocinas(Integer ncocinas) {
        this.ncocinas = ncocinas;
    }
    public Integer getNcomedores() {
        return this.ncomedores;
    }
    
    public void setNcomedores(Integer ncomedores) {
        this.ncomedores = ncomedores;
    }
    public Integer getNestacionamientos() {
        return this.nestacionamientos;
    }
    
    public void setNestacionamientos(Integer nestacionamientos) {
        this.nestacionamientos = nestacionamientos;
    }
    public Boolean getEstadoactual() {
        return this.estadoactual;
    }
    
    public void setEstadoactual(Boolean estadoactual) {
        this.estadoactual = estadoactual;
    }
    public Set getPaquetes() {
        return this.paquetes;
    }
    
    public void setPaquetes(Set paquetes) {
        this.paquetes = paquetes;
    }




}


