package com.persistentes;
// Generated 23/07/2015 03:35:00 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Paquete generated by hbm2java
 */
public class Paquete  implements java.io.Serializable {


     private String codigo;
     private Casaplaya casaplaya;
     private Date fechainicio;
     private Date fechafinal;
     private Float precio;
     private Integer estados;
     private Set pagos = new HashSet(0);
     private Set reservas = new HashSet(0);
     private Set clientes = new HashSet(0);

    public Paquete() {
    }

	
    public Paquete(String codigo, Date fechainicio, Date fechafinal) {
        this.codigo = codigo;
        this.fechainicio = fechainicio;
        this.fechafinal = fechafinal;
    }
    public Paquete(String codigo, Casaplaya casaplaya, Date fechainicio, Date fechafinal, Float precio, Integer estados, Set pagos, Set reservas, Set clientes) {
       this.codigo = codigo;
       this.casaplaya = casaplaya;
       this.fechainicio = fechainicio;
       this.fechafinal = fechafinal;
       this.precio = precio;
       this.estados = estados;
       this.pagos = pagos;
       this.reservas = reservas;
       this.clientes = clientes;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Casaplaya getCasaplaya() {
        return this.casaplaya;
    }
    
    public void setCasaplaya(Casaplaya casaplaya) {
        this.casaplaya = casaplaya;
    }
    public Date getFechainicio() {
        return this.fechainicio;
    }
    
    public void setFechainicio(Date fechainicio) {
        this.fechainicio = fechainicio;
    }
    public Date getFechafinal() {
        return this.fechafinal;
    }
    
    public void setFechafinal(Date fechafinal) {
        this.fechafinal = fechafinal;
    }
    public Float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Float precio) {
        this.precio = precio;
    }
    public Integer getEstados() {
        return this.estados;
    }
    
    public void setEstados(Integer estados) {
        this.estados = estados;
    }
    public Set getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set pagos) {
        this.pagos = pagos;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }




}


