package com.persistentes;
// Generated 23/07/2015 03:35:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Propietario generated by hbm2java
 */
public class Propietario  implements java.io.Serializable {


     private String idpersona;
     private Persona persona;
     private String ncuenta;
     private Set casaplayas = new HashSet(0);

    public Propietario() {
    }

	
    public Propietario(Persona persona) {
        this.persona = persona;
    }
    public Propietario(Persona persona, String ncuenta, Set casaplayas) {
       this.persona = persona;
       this.ncuenta = ncuenta;
       this.casaplayas = casaplayas;
    }
   
    public String getIdpersona() {
        return this.idpersona;
    }
    
    public void setIdpersona(String idpersona) {
        this.idpersona = idpersona;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getNcuenta() {
        return this.ncuenta;
    }
    
    public void setNcuenta(String ncuenta) {
        this.ncuenta = ncuenta;
    }
    public Set getCasaplayas() {
        return this.casaplayas;
    }
    
    public void setCasaplayas(Set casaplayas) {
        this.casaplayas = casaplayas;
    }




}


